# Generated by Django 5.2.6 on 2025-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartorder",
            name="payment",
            field=models.CharField(max_length=50),
        ),
    ]
